steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/streamlit-image",
        ".",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/streamlit-image",
      ]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "website-summarizer",
        "--image",
        "asia-northeast1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/streamlit-image",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--ingress",
        "all",
        "--region",
        "asia-northeast1",
        "--project",
        "${PROJECT_ID}",
        "--quiet",
        "--service-account",
        "sa-build-cicd@${PROJECT_ID}.iam.gserviceaccount.com"
      ]

logsBucket: "gs://cloudbuild_logs_poc"
serviceAccount: "sa-build-cicd@${PROJECT_ID}.iam.gserviceaccount.com"

timeout: 1200s
options:
  logging: GCS_ONLY
